router bgp 600
  bgp router-id 100.200.6.1
  no bgp ebgp-requires-policy
  no bgp network import-check

  neighbor 8.2.4.2 remote-as 330
  neighbor 8.2.4.2 weight 100
  neighbor 8.2.4.3 remote-as 430

  address-family ipv4 unicast
    network 8.1.6.101/32
    network 8.1.6.102/32
  exit-address-family
