ip prefix-list LEFT_FAST seq 5 permit 8.1.1.101/32
ip prefix-list LEFT_FAST seq 10 permit 8.1.1.102/32
ip prefix-list LEFT_FAST seq 15 permit 8.1.5.102/32

ip prefix-list RIGHT_FAST seq 5 permit 8.1.2.101/32
ip prefix-list RIGHT_FAST seq 10 permit 8.1.6.101/32
ip prefix-list RIGHT_FAST seq 15 permit 8.1.6.102/32

route-map RM-LEFT-FAST permit 10
  match ip address prefix-list LEFT_FAST
route-map RM-RIGHT-FAST permit 10
  match ip address prefix-list RIGHT_FAST

router bgp 420
  bgp router-id 100.200.42.1
  no bgp ebgp-requires-policy

  neighbor 8.2.2.11 remote-as 310
  neighbor 8.2.2.12 remote-as 410
  neighbor 8.2.3.31 remote-as 330
  neighbor 8.2.3.32 remote-as 430

  address-family ipv4 unicast
    neighbor 8.2.2.11 route-map RM-RIGHT-FAST out
    neighbor 8.2.2.12 route-map RM-RIGHT-FAST out
    neighbor 8.2.3.31 route-map RM-LEFT-FAST out
    neighbor 8.2.3.32 route-map RM-LEFT-FAST out
  exit-address-family
