ip prefix-list FAST_TO_LEFT seq 5 permit 8.1.2.101/32
ip prefix-list FAST_TO_LEFT seq 10 permit 8.1.6.101/32
ip prefix-list FAST_TO_LEFT seq 15 permit 8.1.6.102/32

ip prefix-list FAST_TO_RIGHT seq 5 permit 8.1.1.101/32
ip prefix-list FAST_TO_RIGHT seq 10 permit 8.1.1.102/32
ip prefix-list FAST_TO_RIGHT seq 15 permit 8.1.5.102/32

route-map RM-FAST-TO-LEFT permit 10
  match ip address prefix-list FAST_TO_LEFT

route-map RM-FAST-TO-RIGHT permit 10
  match ip address prefix-list FAST_TO_RIGHT

router bgp 400
  bgp router-id 100.100.4.1
  no bgp ebgp-requires-policy

  neighbor 8.2.1.1 remote-as 100
  neighbor 8.2.1.4 remote-as 500
  neighbor 8.2.2.1 remote-as 200
  neighbor 8.2.2.4 remote-as 600

  address-family ipv4 unicast
    neighbor 8.2.1.1 route-map RM-FAST-TO-LEFT out
    neighbor 8.2.1.4 route-map RM-FAST-TO-LEFT out
    neighbor 8.2.2.1 route-map RM-FAST-TO-RIGHT out
    neighbor 8.2.2.4 route-map RM-FAST-TO-RIGHT out
  exit-address-family
