ip prefix-list LEFT_SLOW seq 5 permit 8.1.1.101/32
ip prefix-list LEFT_SLOW seq 10 permit 8.1.5.101/32
ip prefix-list LEFT_SLOW seq 15 permit 8.1.5.102/32

ip prefix-list RIGHT_SLOW seq 5 permit 8.1.2.101/32
ip prefix-list RIGHT_SLOW seq 10 permit 8.1.2.102/32
ip prefix-list RIGHT_SLOW seq 15 permit 8.1.6.102/32

route-map RM-LEFT-SLOW permit 10
  match ip address prefix-list LEFT_SLOW
route-map RM-RIGHT-SLOW permit 10
  match ip address prefix-list RIGHT_SLOW

router bgp 310
  bgp router-id 100.200.31.1
  no bgp ebgp-requires-policy

  neighbor 8.2.1.1 remote-as 100
  neighbor 8.2.1.4 remote-as 500
  neighbor 8.2.2.21 remote-as 320
  neighbor 8.2.2.22 remote-as 420

  address-family ipv4 unicast
    neighbor 8.2.1.1 route-map RM-RIGHT-SLOW out
    neighbor 8.2.1.4 route-map RM-RIGHT-SLOW out
    neighbor 8.2.2.21 route-map RM-LEFT-SLOW out
    neighbor 8.2.2.22 route-map RM-LEFT-SLOW out
  exit-address-family
